import { Geist, Geist_Mono } from 'next/font/google';
import { ReduxProvider } from './lib/redux/provider';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body>
                <ReduxProvider>
                    <header className='bg-gray- p-4'>
                        <h1 className='text-2xl font-bold'>My App</h1>
                    </header>
                    <main className='container mx-auto p-4'>{children}</main>
                    <footer className='bg-gray- p-4 text-center'>
                        <p>© 2025 My Next.js App</p>
                    </footer>
                </ReduxProvider>
            </body>
        </html>
    );
}
